Feat/backport kipawo learnings
MakairaIO/storefront-starter-kit pull request #32
Opened 2022-06-20 05:58 UTC by jembach

2022-06-28 10:59 UTC, luflow requested changes

2022-06-28 10:59 UTC, luflow commented on server/index.js
> -    server.get('/sitemap.xml', (req, res) => {
Oh war das echt schon im Starterkit drin? :D Das habe ich voll übersehen - hier könnte man wenigstens auch direkt auf die allLanguages[0] wieder gehen - vielleicht sollten wir es also doch aus dem NGINX rausnehmen und im next abfeiern?

2022-06-28 10:59 UTC, luflow commented
@jembach und es gibt gerade Conflicts ;)

2022-06-28 13:16 UTC, jembach commented on server/index.js
> -    server.get('/sitemap.xml', (req, res) => {
Es macht keinen großen unterschied ob über next oder über den LB. Direkt über den LB reduziert aber die Round Trips. Würde es daher so lassen wie es in der PR ist.

2022-06-28 17:36 UTC, luflow commented on server/index.js
> -    server.get('/sitemap.xml', (req, res) => {
ack.

2022-06-28 17:37 UTC, luflow approved these changes

2022-06-29 15:19 UTC, JanMaeg approved these changes

2022-06-30 16:03 UTC, merged

2022-06-30 16:04 UTC, makaira-github commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/MakairaIO/storefront-starter-kit/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: