ci: add auto sync job that merges or creates a pr in case of an error
MakairaIO/storefront-starter-kit pull request #42
Opened 2022-08-08 12:14 UTC by jembach

2022-08-09 09:57 UTC, AlexanderBabel approved these changes

2022-08-09 13:40 UTC, luflow requested changes

2022-08-09 13:40 UTC, luflow commented on .github/workflows/sync.yml
> +        run: git merge stable --ff-only -m "Merge stable into ${{ matrix.syncBranch }}"
I would prefer rebase here :)

2022-08-10 11:46 UTC, jembach commented on .github/workflows/sync.yml
> +        run: git merge stable --ff-only -m "Merge stable into ${{ matrix.syncBranch }}"
replaced with rebase

2022-08-10 14:42 UTC, merged

2022-08-10 14:44 UTC, makaira-github commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on [GitHub release](https://github.com/MakairaIO/storefront-starter-kit/releases/tag/v1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: